/**
 * Slug generation utility for property URLs.
 *
 * Slug format: <sanitised-title>-<sanitised-city>-<6-char-id-prefix>
 * Example:     "cozy-loft-downtown-paris-a1b2c3"
 *
 * Design decisions:
 *  - The id prefix at the end guarantees global uniqueness without needing a
 *    DB round-trip or a random nonce.
 *  - Title + city give human-readable context.
 *  - Slugs are intentionally stable: regenerating only happens on explicit
 *    request so existing bookmarks / indexed URLs remain valid.
 *  - The SQL function `generate_property_slug` in migration 00024 mirrors
 *    this logic exactly so backfills and server-generated slugs match.
 */

/** Maximum length of the human-readable portion (before the id suffix). */
const BASE_MAX_LENGTH = 60;

/**
 * Convert a free-text string to a URL-safe slug segment.
 * Lowercases, replaces non-alphanumeric runs with hyphens, trims edges.
 */
function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/**
 * Generate a deterministic, URL-safe slug for a property.
 *
 * The slug is built from:
 *   1. The property title  (primary human-readable part)
 *   2. The city            (location context, optional)
 *   3. The first 6 non-hyphen characters of the property UUID (uniqueness suffix)
 *
 * @param title - Property title (required).
 * @param city  - Property city (optional but recommended for readability).
 * @param id    - Property UUID — used to derive the uniqueness suffix.
 *
 * @example
 *   generateSlug('Cozy Loft Downtown', 'Paris', 'a1b2c3d4-...')
 *   // → 'cozy-loft-downtown-paris-a1b2c3'
 */
export function generateSlug(title: string, city: string | undefined | null, id: string): string {
  const titlePart = slugify(title || 'property');
  const cityPart  = city ? slugify(city) : '';

  // Combine non-empty parts
  const parts  = [titlePart, cityPart].filter(Boolean);
  let   base   = parts.join('-');

  // Truncate to keep URLs manageable
  if (base.length > BASE_MAX_LENGTH) {
    base = base.slice(0, BASE_MAX_LENGTH);
    // Trim a trailing hyphen that truncation may have introduced
    base = base.replace(/-+$/, '');
  }

  // 6-char suffix from the UUID (strip hyphens, take first 6 chars)
  const suffix = id.replace(/-/g, '').slice(0, 6);

  return `${base}-${suffix}`;
}

/**
 * Extract the property id suffix embedded in a slug.
 *
 * The backend route uses this to look up the property by id without a full
 * slug → id join, making the lookup O(1) on the primary key index.
 *
 * @param slug - A slug previously generated by `generateSlug`.
 * @returns The 6-char id prefix, or null if the slug format is unrecognised.
 *
 * @example
 *   extractIdSuffix('cozy-loft-downtown-paris-a1b2c3') // → 'a1b2c3'
 */
export function extractIdSuffix(slug: string): string | null {
  const parts = slug.split('-');
  if (parts.length < 2) return null;
  const last = parts[parts.length - 1];
  // Must be 6 lowercase hex characters
  return /^[a-z0-9]{6}$/.test(last) ? last : null;
}

/**
 * Determine whether a given string could be a valid property slug.
 * Used for input validation before a DB lookup.
 */
export function isValidSlug(value: string): boolean {
  // lowercase alphanumeric words joined by hyphens, ends with 6-char suffix
  return /^[a-z0-9]+(-[a-z0-9]+)*$/.test(value) && value.length <= 200;
}
